version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      -  DB_HOST=krev-postgresql
      -  DB_DATABASE=testing
      -  DB_USERNAME=testing_login
      -  DB_PASSWORD=testing
      -  DB_CONNECTION=pgsql
      -  DB_PORT=5432
      -  KREV_K_NUMBER=5
      -  KREV_EV_DELAY=48
      -  KREV_IDENTITY_HOST=krev-identity
      -  KREV_IDENTITY_PORT=50051
      -  KREV_MEMO_MIN_LENGTH=3
      -  KREV_EV_MEMO_VISIBLE=false
      -  APP_DEBUG=true
    depends_on:
      - mariadb
    ports:
      - 2000:3000
    volumes:
      - ./:/app
